# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1a\n\nsearchinfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\x08songinfo\x12\r\n\x05lyric\x18\x01 \x01(\t24\n\tMyService\x12\'\n\x0bSearchLyric\x12\x0b.searchinfo\x1a\t.songinfo\"\x00\x42\x0bZ\t./linebotb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t./linebot'
  _SEARCHINFO._serialized_start=17
  _SEARCHINFO._serialized_end=43
  _SONGINFO._serialized_start=45
  _SONGINFO._serialized_end=70
  _MYSERVICE._serialized_start=72
  _MYSERVICE._serialized_end=124
# @@protoc_insertion_point(module_scope)
